name: paper_shorts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.44.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.4
  - pip=23.3.1
  - python=3.10.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.44.0
  - tk=8.6.13
  - wheel=0.41.3
  - xz=5.2.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - coloredlogs==15.0.1
      - contourpy==1.2.0
      - cryptography==41.0.5
      - cycler==0.12.1
      - dataclasses-json==0.6.2
      - decorator==5.1.1
      - effdet==0.4.1
      - emoji==2.8.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - filelock==3.13.1
      - filetype==1.2.0
      - flatbuffers==23.5.26
      - fonttools==4.45.0
      - fsspec==2023.10.0
      - huggingface-hub==0.19.4
      - humanfriendly==10.0
      - idna==3.4
      - iopath==0.1.10
      - ipython==8.17.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - keyboard==0.13.5
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - layoutparser==0.3.4
      - lxml==4.9.3
      - markdown==3.5.1
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - msg-parser==1.2.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - nltk==3.8.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - olefile==0.46
      - omegaconf==2.3.0
      - onnx==1.15.0
      - onnxruntime==1.15.1
      - opencv-python==4.8.1.78
      - openpyxl==3.1.2
      - packaging==23.2
      - pandas==2.1.3
      - parso==0.8.3
      - pdf2image==1.16.3
      - pdfminer-six==20221105
      - pdfplumber==0.10.3
      - pexpect==4.8.0
      - pillow==10.1.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycocotools==2.0.7
      - pycparser==2.21
      - pygments==2.17.1
      - pypandoc==1.12
      - pyparsing==3.1.1
      - pypdfium2==4.24.0
      - pytesseract==0.3.10
      - python-dateutil==2.8.2
      - python-docx==1.1.0
      - python-iso639==2023.6.15
      - python-magic==0.4.27
      - python-multipart==0.0.6
      - python-pptx==0.6.23
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - rapidfuzz==3.5.2
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.0
      - scipy==1.11.4
      - six==1.16.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - timm==0.9.11
      - tokenizers==0.15.0
      - torch==2.1.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - traitlets==5.13.0
      - transformers==4.35.2
      - triton==2.1.0
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - unstructured==0.11.0
      - unstructured-inference==0.7.15
      - unstructured-pytesseract==0.3.12
      - urllib3==2.1.0
      - wcwidth==0.2.11
      - wrapt==1.16.0
      - xlrd==2.0.1
      - xlsxwriter==3.1.9
